version: "3.9"

services:
  kkbox:
    build: .
    container_name: kkbox-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
      - ./src:/app/src
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true