version: "3.9"

services:
  kkbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/cygnussec/kkbox-churn-kkbox:latest
    container_name: kkbox-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    working_dir: /app
    tty: true
    stdin_open: true